[2024-09-23T12:53:56.558+0100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-23T12:53:56.569+0100] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: office365_email_dag.send_email manual__2024-09-23T11:53:53.174182+00:00 [queued]>
[2024-09-23T12:53:56.575+0100] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: office365_email_dag.send_email manual__2024-09-23T11:53:53.174182+00:00 [queued]>
[2024-09-23T12:53:56.575+0100] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-23T12:53:56.585+0100] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): send_email> on 2024-09-23 11:53:53.174182+00:00
[2024-09-23T12:53:56.587+0100] {standard_task_runner.py:72} INFO - Started process 24074 to run task
[2024-09-23T12:53:56.594+0100] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'office365_email_dag', 'send_email', 'manual__2024-09-23T11:53:53.174182+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/send_email.py', '--cfg-path', '/var/folders/fs/b76k8hkn5gdc__ng0088py8c0000gq/T/tmp5nkx0f7g']
[2024-09-23T12:53:56.596+0100] {standard_task_runner.py:105} INFO - Job 21: Subtask send_email
[2024-09-23T12:53:56.637+0100] {task_command.py:467} INFO - Running <TaskInstance: office365_email_dag.send_email manual__2024-09-23T11:53:53.174182+00:00 [running]> on host robbies-mbp.lan
[2024-09-23T12:53:56.702+0100] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='office365_email_dag' AIRFLOW_CTX_TASK_ID='send_email' AIRFLOW_CTX_EXECUTION_DATE='2024-09-23T11:53:53.174182+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-23T11:53:53.174182+00:00'
[2024-09-23T12:53:56.704+0100] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-23T12:53:56.704+0100] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-23T12:53:56.705+0100] {logging_mixin.py:190} INFO - Current task name:send_email state:running start_date:2024-09-23 11:53:56.569523+00:00
[2024-09-23T12:53:56.705+0100] {logging_mixin.py:190} INFO - Dag name:office365_email_dag and current dag run status:running
[2024-09-23T12:53:56.706+0100] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-23T12:53:56.717+0100] {base.py:84} INFO - Retrieving connection 'smtp_default'
[2024-09-23T12:53:56.718+0100] {email.py:272} INFO - Email alerting: attempt 1
[2024-09-23T12:54:02.116+0100] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/rtewelde/airflow_venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rtewelde/airflow_venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rtewelde/airflow_venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rtewelde/airflow_venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rtewelde/airflow_venv/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rtewelde/airflow_venv/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rtewelde/airflow_venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rtewelde/airflow/dags/send_email.py", line 14, in send_email
    send_email_smtp(to=to, subject=subject, html_content=html_content)
  File "/Users/rtewelde/airflow_venv/lib/python3.11/site-packages/airflow/utils/email.py", line 155, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/Users/rtewelde/airflow_venv/lib/python3.11/site-packages/airflow/utils/email.py", line 282, in send_mime_email
    smtp_conn.login(smtp_user, smtp_password)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/smtplib.py", line 750, in login
    raise last_exception
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/smtplib.py", line 739, in login
    (code, resp) = self.auth(
                   ^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.139 Authentication unsuccessful, basic authentication is disabled. [LO4P265CA0200.GBRP265.PROD.OUTLOOK.COM 2024-09-23T11:54:02.062Z 08DCDB4B210DB370]')
[2024-09-23T12:54:02.130+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-23T12:54:02.131+0100] {logging_mixin.py:190} INFO - Task start:2024-09-23 11:53:56.569523+00:00 end:2024-09-23 11:54:02.130311+00:00 duration:5.560788
[2024-09-23T12:54:02.132+0100] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): send_email> dag:<DAG: office365_email_dag> dagrun:<DagRun office365_email_dag @ 2024-09-23 11:53:53.174182+00:00: manual__2024-09-23T11:53:53.174182+00:00, state:running, queued_at: 2024-09-23 11:53:53.189607+00:00. externally triggered: True>
[2024-09-23T12:54:02.132+0100] {logging_mixin.py:190} INFO - Failure caused by (535, b'5.7.139 Authentication unsuccessful, basic authentication is disabled. [LO4P265CA0200.GBRP265.PROD.OUTLOOK.COM 2024-09-23T11:54:02.062Z 08DCDB4B210DB370]')
[2024-09-23T12:54:02.133+0100] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=office365_email_dag, task_id=send_email, run_id=manual__2024-09-23T11:53:53.174182+00:00, execution_date=20240923T115353, start_date=20240923T115356, end_date=20240923T115402
[2024-09-23T12:54:02.142+0100] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-23T12:54:02.142+0100] {standard_task_runner.py:124} ERROR - Failed to execute job 21 for task send_email ((535, b'5.7.139 Authentication unsuccessful, basic authentication is disabled. [LO4P265CA0200.GBRP265.PROD.OUTLOOK.COM 2024-09-23T11:54:02.062Z 08DCDB4B210DB370]'); 24074)
Traceback (most recent call last):
  File "/Users/rtewelde/airflow_venv/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rtewelde/airflow_venv/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rtewelde/airflow_venv/lib/python3.11/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/rtewelde/airflow_venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rtewelde/airflow_venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rtewelde/airflow_venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/Users/rtewelde/airflow_venv/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rtewelde/airflow_venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/Users/rtewelde/airflow_venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/rtewelde/airflow_venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rtewelde/airflow_venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rtewelde/airflow_venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rtewelde/airflow_venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rtewelde/airflow_venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rtewelde/airflow_venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rtewelde/airflow_venv/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rtewelde/airflow_venv/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rtewelde/airflow_venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rtewelde/airflow/dags/send_email.py", line 14, in send_email
    send_email_smtp(to=to, subject=subject, html_content=html_content)
  File "/Users/rtewelde/airflow_venv/lib/python3.11/site-packages/airflow/utils/email.py", line 155, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/Users/rtewelde/airflow_venv/lib/python3.11/site-packages/airflow/utils/email.py", line 282, in send_mime_email
    smtp_conn.login(smtp_user, smtp_password)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/smtplib.py", line 750, in login
    raise last_exception
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/smtplib.py", line 739, in login
    (code, resp) = self.auth(
                   ^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.139 Authentication unsuccessful, basic authentication is disabled. [LO4P265CA0200.GBRP265.PROD.OUTLOOK.COM 2024-09-23T11:54:02.062Z 08DCDB4B210DB370]')
[2024-09-23T12:54:02.177+0100] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-23T12:54:02.192+0100] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-23T12:54:02.193+0100] {local_task_job_runner.py:245} INFO - ::endgroup::
